title: TLDAG
description: TLDAG

email: tldag.ch@gmail.com
twitter_username: tldag
github_username:  tldag

domain: tldag.github.io

url: https://tldag.github.io
#baseurl: /tldag.github.io

remote_theme: tldag/tldag-markdown-layout

exclude: [LICENSE, README.md, Gemfile]
